""""add_master_recommendations"

Revision ID: 37e662d11adf
Revises: 4812ea6b4d24
Create Date: 2026-03-09 00:31:55.963655
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e662d11adf'
down_revision: Union[str, None] = '4812ea6b4d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strength_level', sa.String(length=10), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_master_recommendations_created_by_users')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_master_recommendations_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_recommendations'))
    )
    op.create_index(op.f('ix_master_recommendations_created_by'), 'master_recommendations', ['created_by'], unique=False)
    op.create_index(op.f('ix_master_recommendations_venue_id'), 'master_recommendations', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_recommendations_venue_id'), table_name='master_recommendations')
    op.drop_index(op.f('ix_master_recommendations_created_by'), table_name='master_recommendations')
    op.drop_table('master_recommendations')
    # ### end Alembic commands ###
