"""add_guest_login_fields

Revision ID: 5de59e930c0a
Revises: ea40338ddd90
Create Date: 2026-03-08 17:13:35.278969
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de59e930c0a'
down_revision: Union[str, None] = 'ea40338ddd90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('guests', sa.Column('login_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('guests', sa.Column('telegram_blocked', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'telegram_blocked')
    op.drop_column('guests', 'login_count')
    op.drop_column('guests', 'last_login_at')
    # ### end Alembic commands ###
