""""add_public_id_and_guest_name_to_hookah_orders"

Revision ID: 84b865dd2718
Revises: d09c130b7cdb
Create Date: 2026-03-10 03:01:39.739607
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b865dd2718'
down_revision: Union[str, None] = 'd09c130b7cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hookah_orders', sa.Column('public_id', sa.Text(), nullable=True))
    op.add_column('hookah_orders', sa.Column('guest_name', sa.Text(), nullable=True))
    op.create_index(op.f('ix_hookah_orders_public_id'), 'hookah_orders', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hookah_orders_public_id'), table_name='hookah_orders')
    op.drop_column('hookah_orders', 'guest_name')
    op.drop_column('hookah_orders', 'public_id')
    # ### end Alembic commands ###
