"""initial schema

Revision ID: ea40338ddd90
Revises: 
Create Date: 2026-02-28 18:56:34.663043
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea40338ddd90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_encrypted', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('telegram_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests'))
    )
    op.create_index(op.f('ix_guests_phone_hash'), 'guests', ['phone_hash'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('floor_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('shape', sa.Enum('rect', 'circle', name='tableshape'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_tables_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tables')),
    sa.UniqueConstraint('venue_id', 'number', name='uq_table_venue_number')
    )
    op.create_index(op.f('ix_tables_venue_id'), 'tables', ['venue_id'], unique=False)
    op.create_table('tobaccos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('flavor_profile', sa.JSON(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('weight_available_grams', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('strength >= 1 AND strength <= 5', name=op.f('ck_tobaccos_strength_range')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_tobaccos_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tobaccos'))
    )
    op.create_index(op.f('ix_tobaccos_venue_id'), 'tobaccos', ['venue_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'hookah_master', name='userrole'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_users_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_index(op.f('ix_users_venue_id'), 'users', ['venue_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('guest_phone_encrypted', sa.String(length=200), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=False),
    sa.Column('time_to', sa.Time(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('guest_count > 0', name=op.f('ck_bookings_guest_count_positive')),
    sa.CheckConstraint('time_from < time_to', name=op.f('ck_bookings_time_order')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_bookings_guest_id_guests')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_bookings_table_id_tables')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_bookings_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index('ix_booking_conflict', 'bookings', ['table_id', 'date', 'time_from', 'time_to'], unique=False)
    op.create_index(op.f('ix_bookings_guest_id'), 'bookings', ['guest_id'], unique=False)
    op.create_index(op.f('ix_bookings_table_id'), 'bookings', ['table_id'], unique=False)
    op.create_index(op.f('ix_bookings_venue_id'), 'bookings', ['venue_id'], unique=False)
    op.create_table('hookah_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'preparing', 'served', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('strength >= 1 AND strength <= 5', name=op.f('ck_hookah_orders_strength_range')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_hookah_orders_booking_id_bookings')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_hookah_orders_guest_id_guests')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_hookah_orders_table_id_tables')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_hookah_orders_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hookah_orders'))
    )
    op.create_index(op.f('ix_hookah_orders_booking_id'), 'hookah_orders', ['booking_id'], unique=False)
    op.create_index(op.f('ix_hookah_orders_guest_id'), 'hookah_orders', ['guest_id'], unique=False)
    op.create_index(op.f('ix_hookah_orders_table_id'), 'hookah_orders', ['table_id'], unique=False)
    op.create_index(op.f('ix_hookah_orders_venue_id'), 'hookah_orders', ['venue_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('tobacco_id', sa.Integer(), nullable=False),
    sa.Column('weight_grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['hookah_orders.id'], name=op.f('fk_order_items_order_id_hookah_orders')),
    sa.ForeignKeyConstraint(['tobacco_id'], ['tobaccos.id'], name=op.f('fk_order_items_tobacco_id_tobaccos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_tobacco_id'), 'order_items', ['tobacco_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_tobacco_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_hookah_orders_venue_id'), table_name='hookah_orders')
    op.drop_index(op.f('ix_hookah_orders_table_id'), table_name='hookah_orders')
    op.drop_index(op.f('ix_hookah_orders_guest_id'), table_name='hookah_orders')
    op.drop_index(op.f('ix_hookah_orders_booking_id'), table_name='hookah_orders')
    op.drop_table('hookah_orders')
    op.drop_index(op.f('ix_bookings_venue_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_table_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guest_id'), table_name='bookings')
    op.drop_index('ix_booking_conflict', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_venue_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tobaccos_venue_id'), table_name='tobaccos')
    op.drop_table('tobaccos')
    op.drop_index(op.f('ix_tables_venue_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_table('venues')
    op.drop_index(op.f('ix_guests_phone_hash'), table_name='guests')
    op.drop_table('guests')
    # ### end Alembic commands ###
